sudo: required
services:
  - docker

before_install:
  - docker build -t noamros9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true noamros9/docker-react npm run test


notifications:
  email: false